import fs from 'node:fs';
import cp from 'node:child_process';
import path from 'node:path';
const root=path.resolve('.');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const json=p=>JSON.parse(read(p));
const fail=m=>{throw new Error(m)};
for(const f of ['app.js','sw.js','data-inline.js','cloudflare-worker/worker.js']) cp.execFileSync(process.execPath,['--check',path.join(root,f)],{stdio:'inherit'});
const kanji=json('data/kanji-450-source.json').records;
const papers=json('data/past-papers.json');
const evidence=json('data/past-paper-evidence-bank-v2.json').questions;
const sources=json('data/source-catalog.json');
if(kanji.length!==450) fail('Kanji count is not 450');
const paperCount=papers.reduce((n,p)=>n+p.questions.length,0); if(paperCount!==211) fail('Past-paper question count is not 211');
if(evidence.length!==211) fail('Evidence count is not 211');
if(sources.length!==18) fail('Source catalog count is not 18');
const ek=new Set(evidence.map(x=>`${x.paper_id}:${x.question_no}`)); if(ek.size!==211) fail('Evidence paper/question keys are not unique');
const removed=['Final_Cleaned_YouTube_Transcript_Study_Notes_2026-10-06(1)','Japanese_All_in_One_FINAL_Study_Note_V2_4LANG_RENDERED(1)'];
const allFiles=[];(function walk(d){for(const x of fs.readdirSync(d,{withFileTypes:true})){if(['node_modules','.git'].includes(x.name))continue;const p=path.join(d,x.name);if(x.isDirectory())walk(p);else allFiles.push(p)}})(root);
for(const bad of removed) if(allFiles.some(f=>f.includes(bad))) fail('Removed source unexpectedly present: '+bad);
if(!read('sw.js').includes('jft-master-v16-final-release')) fail('Final SW cache version missing');
if(!read('cloudflare-worker/wrangler.toml').includes('name = "i-jft"')) fail('Worker name is not i-jft');
const worker=await import('file://'+path.join(root,'cloudflare-worker/worker.js'));
const env={};
let r=await worker.default.fetch(new Request('https://example.test/ocr',{method:'OPTIONS'}),env); if(r.status!==204) fail('Worker OPTIONS contract failed');
r=await worker.default.fetch(new Request('https://example.test/ocr',{method:'GET'}),env); if(r.status!==405) fail('Worker method contract failed');
r=await worker.default.fetch(new Request('https://example.test/ocr',{method:'POST',headers:{'content-type':'application/json'},body:'{}'}),env); if(r.status!==503) fail('Worker missing-secret guard failed');
console.log(JSON.stringify({status:'PASS',syntax:'PASS',kanji:450,past_papers:211,evidence:211,sources:18,removed_sources_absent:true,worker_contract:'PASS',live_gemini_ocr:'NOT_TESTED',live_cloudflare_deployment:'NOT_TESTED'},null,2));
